### ISSUE TITLE
Allow for validation of private Orbs

### ISSUE THREAD

**Issue by jamesggraf-m1** [zahorniak/pre-commit-circleci#4]
Love the plugin, but if you try to use this with a private orb you get an error like this:
Error: Cannot find namespace/private-orb@1.0.1 in the orb registry. Check that the namespace, orb name and version are correct.

**Comment by zahorniak** [comment]
@jamesggraf-m1 I do not maintain private orbs and can't test it properly. I would appreciate it if you create a Pull Request with the requested changes.

**Comment by zahorniak** [comment]
This feature was released in [v0.4](https://github.com/zahorniak/pre-commit-circleci/releases/tag/v0.4)
