### ISSUE TITLE
Add support for multiple config files

### ISSUE THREAD

**Issue by nimakalantar** [zahorniak/pre-commit-circleci#8]
CircleCI has a dynamic config option: https://circleci.com/docs/dynamic-config/

This can look like:
```
.circleci/
 - config.yml
 - continue_config.yml
```

These files should both be validated.

Edit: https://github.com/zahorniak/pre-commit-circleci/issues/8#issuecomment-1323743945

**Comment by zahorniak** [comment]
@nimakalantar, thanks for the suggestion. I will take a look next week at how to implement these checks.

**Comment by zahorniak** [comment]
Hi @nimakalantar. I spent a few hours but didn't find the right solution.
If you want to help, feel free to create a pull request for this feature

**Comment by nimakalantar** [comment]
I will look into it, probably the simplest solution I can think would require the following changes:
- allow the user to specify the config file to be validated through an arg, e.g. default can be `config.yml`
- allow the user to pass in a binary arg that determines whether the config specified is to be processed 
- if a config is processed, run the validate command on the processed file, and delete after for cleanup

**Comment by nimakalantar** [comment]
I just realised something: we could just skip the second requirement of passing an arg by just processing all files that are passed, I've just tried processing a standard `config.yml` and it doesn't seem to do many changes that are important.
This isn't the cleanest solution though..

**Comment by zahorniak** [comment]
@nimakalantar I agree that implementing this might be slightly complicated in bash. Go ahead with your solution 👍🏼
